apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::160382898307:role/eksctl-tracker-eks-nodegroup-ng-1-NodeInstanceRole-KoLYJ1Y7LbK9
      groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::160382898307:role/github.ecr.oicd
      groups:
        - system:masters
      username: github
