---
apiVersion: v1
kind: Namespace
metadata:
  name: tracker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker
  namespace: tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tracker
  template:
    metadata:
      labels:
        app: tracker
    spec:
      containers:
        - name: tracker
          image: 160382898307.dkr.ecr.eu-central-1.amazonaws.com/tracker:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: tracker
  namespace: tracker
spec:
  type: LoadBalancer
  selector:
    app: tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
