name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build and Test with Maven
        run: mvn clean verify

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::160382898307:role/github.ecr.oicd
          aws-region: eu-central-1

      - name: Log in to AWS ecr
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push to AWS ECR
        env:
          REGISTRY: ${{steps.ecr-login.outputs.registry}}
          REPOSITORY: tracker
          IMAGE_TAG: ${{github.sha}}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:${{ github.sha }} \
                       -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY:${{ github.sha }}
          docker push $REGISTRY/$REPOSITORY:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::160382898307:role/github.ecr.oicd
          aws-region: eu-central-1

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name tracker-eks --region eu-central-1

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8/tracker.yaml

      - name: Roll out new image
        env:
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          REPOSITORY: tracker
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl set image -n tracker deployment/tracker tracker=$REGISTRY/$REPOSITORY:${IMAGE_TAG}
          kubectl rollout status -n tracker deployment/tracker --timeout=120s
